%% Maximum Likelihood Estiamtion of Two-stage RT model
addpath('../Data/rt_model')

%% Data preparation
data_ts2_flex_decay_stop = readtable('ts2_flex_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts2_flex_decay = readtable('ts2_flex_decay_rt.csv','FileEncoding','UTF-8');
data_ts_flex_decay_stop = readtable('ts_flex_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts_flex_decay = readtable('ts_flex_decay_rt.csv','FileEncoding','UTF-8');
data_ts2_decay_stop = readtable('ts2_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts2_decay = readtable('ts2_decay_rt.csv','FileEncoding','UTF-8');
data_ts_decay_stop = readtable('ts_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts_decay = readtable('ts_decay_rt.csv','FileEncoding','UTF-8');
data_ts2_ratio_decay_stop = readtable('ts2_ratio_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts2_ratio_decay = readtable('ts2_ratio_decay_rt.csv','FileEncoding','UTF-8');
data_ts_ratio_decay_stop = readtable('ts_ratio_decay_stop_rt.csv','FileEncoding','UTF-8');
data_ts_ratio_decay = readtable('ts_ratio_decay_rt.csv','FileEncoding','UTF-8');
data_os_decay = readtable('os_decay_rt.csv','FileEncoding','UTF-8');
data_os_costOnly = readtable('os_costOnly_rt.csv','FileEncoding','UTF-8');
data_os_evidenceOnly = readtable('os_evidenceOnly_rt.csv','FileEncoding','UTF-8');
data_os = readtable('os_rt.csv','FileEncoding','UTF-8');

%% Preferences
p = [];
% Optimatization options
options = optimoptions('fmincon','Display','none','Algorithm','interior-point','MaxIter',1e5);
% Repeat times of modeling
rep_times = 250;
% Start parallel computing task
if max(size(gcp)) == 0
    parpool;
end

%% Model fitting

%% ts2_flex_decay_stop
ts2_flex_decay_stop_est = two_stage_rt2_model(data_ts2_flex_decay_stop,...
    rep_times,options,...
    'ts2_flex_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts2_flex_decay
ts2_flex_decay_est = two_stage_rt2_model(data_ts2_flex_decay,...
    rep_times,options,...
    'ts2_flex_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_flex_decay_stop
ts_flex_decay_stop_est = two_stage_rt2_model(data_ts_flex_decay_stop,...
    rep_times,options,...
    'ts_flex_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_flex_decay
ts_flex_decay_est = two_stage_rt2_model(data_ts_flex_decay,...
    rep_times,options,...
    'ts_flex_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts2_decay_stop
ts2_decay_stop_est = two_stage_rt2_model(data_ts2_decay_stop,...
    rep_times,options,...
    'ts2_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts2_decay
ts2_decay_est = two_stage_rt2_model(data_ts2_decay,...
    rep_times,options,...
    'ts2_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_decay_stop
ts_decay_stop_est = two_stage_rt2_model(data_ts_decay_stop,...
    rep_times,options,...
    'ts_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_decay
ts_decay_est = two_stage_rt2_model(data_ts_decay,...
    rep_times,options,...
    'ts_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts2_ratio_decay_stop
ts2_ratio_decay_stop_est = two_stage_rt2_model(data_ts2_ratio_decay_stop,...
    rep_times,options,...
    'ts2_ratio_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts2_ratio_decay
ts2_ratio_decay_est = two_stage_rt2_model(data_ts2_ratio_decay,...
    rep_times,options,...
    'ts2_ratio_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_ratio_decay_stop
ts_ratio_decay_stop_est = two_stage_rt2_model(data_ts_ratio_decay_stop,...
    rep_times,options,...
    'ts_ratio_decay_stop',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% ts_ratio_decay
ts_ratio_decay_est = two_stage_rt2_model(data_ts_ratio_decay,...
    rep_times,options,...
    'ts_ratio_decay',...
    {'a1','b1','gamma1','sigma1','a2','b2','gamma2','sigma2'},...
    false,true,false,p);

%% os_decay
os_decay_est = one_stage_rt_model(data_os_decay,...
    rep_times,options,...
    'os_decay',...
    {'a1','b1','gamma1','sigma1'},...
    false,true,false,p);

%% os_costOnly
os_costOnly_est = one_stage_rt_model(data_os_costOnly,...
    rep_times,options,...
    'os_costOnly',...
    {'a1','b1','gamma1','sigma1'},...
    false,true,false,p);

%% os_evidenceOnly
os_evidenceOnly_est = one_stage_rt_model(data_os_evidenceOnly,...
    rep_times,options,...
    'os_evidenceOnly',...
    {'a1','b1','gamma1','sigma1'},...
    false,true,false,p);

%% os
os_est = one_stage_rt_model(data_os,...
    rep_times,options,...
    'os',...
    {'a1','b1','gamma1','sigma1'},...
    false,true,false,p);

