%% Maximum Likelihood Estiamtion of Bead-Drawing Model

%% Data preparation
o_data = readtable('../../Data/nobm_w_info.csv');
data = o_data(o_data.draw~=20,:);

data_c = data;
data_c.ratio_46 = double(abs(data_c.ratio-log(0.6/0.4))<sqrt(eps));
data_c.ratio_28 = double(abs(data_c.ratio-log(0.8/0.2))<sqrt(eps));

% The positions of variables in the dataframe/datatable
% -----------------------
% #     |Vars           |
% -----------------------
% 3     |kConst         |
% 4     |ratio          |
% 5     |cost           |
% 6     |cum_info       |
% 7     |draw           |
% 8     |online_cost    |
% 9     |last_dt        |
% 10    |last_cr        |
% 11    |stop           |
% 12    |cum_info_val   |
% 13    |cost0          |
% 14    |cost0_1        |
% 15    |cost0_4        |
% 16    |info           |
% 17    |ratio_46       |
% 18    |ratio_28       |
% -----------------------

%% Preferences
p = [];

% Optimatization options
options.default = optimoptions('fmincon','Display','none',...
    'Algorithm','sqp','MaxIterations',10000,...
    'MaxFunctionEvaluations',30000,'SpecifyObjectiveGradient',false,...
    'ScaleProblem',true);
options.backup = optimoptions('fmincon','Display','none',...
    'Algorithm','interior-point','MaxIterations',10000,...
    'MaxFunctionEvaluations',30000,'SpecifyObjectiveGradient',false,...
    'ScaleProblem',true);

% Repeat times of modeling
rep_times = 1000;

% Start parallel computing task
if max(size(gcp)) == 0
    parpool;
end

%% One-stage models

%% One-stage model: cost + evidence w/o decay
if true
    os = one_step_model(data,[3,4,6,12,14,15,7:10],11,rep_times,options,'os',...
        {'b0','bU','bE','bEv','bC0_1','bC0_4','bN','bOC','bPN','bPR'},false,true,false,p);
end

%% One-stage model: w/0 Evidence
if true
    os_costOnly = one_step_model(data,[3,14,15,7,8],11,rep_times,options,'os_costOnly',...
        {'b0','bC0_1','bC0_4','bN','bOC'},false,true,false,p);
end

%% One-stage model: w/0 Cost
if true
    os_evidenceOnly = one_step_model(data,[3,4,6,12,9,10],11,rep_times,options,'os_evidenceOnly',...
        {'b0','bU','bE','bEv','bPN','bPR'},false,true,false,p);
end

%% One-stage full decay model
os_decay_est = one_step_decay_model(data,[],[3,4,6,12,14,15,7:10],11,[4,6,12,16,7],rep_times,options,'os_decay',...
        {'b0','bU','bE','bEv','bC0_1','bC0_4','bN','bOC','bPN','bPR','alpha'},false,true,false,p);

%% Two-stage full decay model: C to E
ts_decay_est = two_step_decay_model(data,[],[3,14,15,7,8],...
        [3,4,6,12,9,10],13:15,11,[4,6,12,16,7],rep_times,options,'ts_decay',...
        {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','ptr0','ptr1','ptr4','alpha'},...
        false,true,false,p);

%% Two-stage full decay model+: C to E + stop_to_next
ts_decay_stop_est = two_step_decay_model(data_c,[],false,[3,14,15,7,8],...
    [3,4,6,12,9,10],13:15,11,[4,6,12,16,7],rep_times,options,'ts_decay_stop',...
    {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','ptr0','ptr1','ptr4','alpha'},...
    false,true,false,p);

%% Two-stage full decay model: E to C
ts2_decay_est = two_step_decay_model(data,[],[3,4,6,12,9,10],...
        [3,14,15,7,8],13:15,11,[4,6,12,16,7],rep_times,options,'ts2_decay',...
        {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','ptr0','ptr1','ptr4','alpha'},...
        false,true,false,p);

%% Two-stage full decay model+: E to C + stop_to_next
ts2_decay_stop_est = two_step_decay_model(data_c,[],false,[3,4,6,12,9,10],...
    [3,14,15,7,8],13:15,11,[4,6,12,16,7],rep_times,options,'ts2_decay_stop',...
    {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','ptr0','ptr1','ptr4','alpha'},...
    false,true,false,p);

ts_ratio_decay_est = two_step_decay_model(data_c,[],[3,14,15,7,8],...
        [3,4,6,12,9,10],17:18,11,[4,6,12,16,7],rep_times,options,'ts_ratio_decay',...
        {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','ptr46','ptr28','alpha'},...
        false,true,false,p);

% + stop_to_second
ts_ratio_decay_stop_est = two_step_decay_model(data_c,[],false,[3,14,15,7,8],...
    [3,4,6,12,9,10],17:18,11,[4,6,12,16,7],rep_times,options,'ts_ratio_decay_stop',...
    {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','ptr46','ptr28','alpha'},...
    false,true,false,p);

ts2_ratio_decay_est = two_step_decay_model(data_c,[],[3,4,6,12,9,10],...
        [3,14,15,7,8],17:18,11,[4,6,12,16,7],rep_times,options,'ts2_ratio_decay',...
        {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','ptr46','ptr28','alpha'},...
        false,true,false,p);

% + stop_to_second
ts2_ratio_decay_stop_est = two_step_decay_model(data_c,[],false,[3,4,6,12,9,10],...
    [3,14,15,7,8],17:18,11,[4,6,12,16,7],rep_times,options,'ts2_ratio_decay_stop',...
    {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','ptr46','ptr28','alpha'},...
    false,true,false,p);

%% Two-stage of flexible second-thought probability with decay
ts_flex_decay_est = two_step_flex_decay_model(data_c,[],true,[3,14,15,7,8],...
        [3,4,6,12,9,10],11,[4,6,12,16,7],rep_times,options,'ts_flex_decay',...
        {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','k','b','alpha'},...
        false,true,false,p);

ts2_flex_decay_est = two_step_flex_decay_model(data_c,[],true,[3,4,6,12,9,10],...
        [3,14,15,7,8],11,[4,6,12,16,7],rep_times,options,'ts2_flex_decay',...
        {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','k','b','alpha'},...
        false,true,false,p);

%% Two-stage of flexible second-thought probability with decay + stop then second-thought
ts_flex_decay_stop_est = two_step_flex_decay_model(data_c,[],false,[3,14,15,7,8],...
        [3,4,6,12,9,10],11,[4,6,12,16,7],rep_times,options,'ts_flex_decay_stop',...
        {'bkC','bC0_1','bC0_4','bN','bOC','bkE','bU','bE','bEv','bPN','bPR','k','b','alpha'},...
        false,true,false,p);
ts2_flex_decay_stop_est = two_step_flex_decay_model(data_c,[],false,[3,4,6,12,9,10],...
        [3,14,15,7,8],11,[4,6,12,16,7],rep_times,options,'ts2_flex_decay_stop',...
        {'bkE','bU','bE','bEv','bPN','bPR','bkC','bC0_1','bC0_4','bN','bOC','k','b','alpha'},...
        false,true,false,p);

%% After modeling
delete(gcp('nocreate'));
